### ISSUE TITLE
Image is much bigger than necessary

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/hashbang.sh#102]
The image contains:
1. [ ] a complete build environment, `python-dev`, `libssl-dev`, `libldap2-dev`, `libsasl2-dev`;
2. [ ] `pip` and a bunch of packages installed through it;
3. [ ] many libraries specified in `requirements.txt` whose usefulness is unclear.

We can get rid of 1. by using Debian packages for the not-pure-Python dependencies, and potentially even 2.
3. is potentially more annoying, due to there being more iterations and testing involved.

**Comment by daurnimator** [comment]
Is this done now with #107 merged?

**Comment by KellerFuchs** [comment]
@daurnimator Right.
