### ISSUE TITLE
The signup services appear to be down

### ISSUE THREAD

**Issue by ev1l0rd** [hashbang/hashbang.sh#125]
Or at least, hashbang.sh freezes when I try to run it and curling https://hashbang.sh/server/stats just makes curl sit there and do nothing.

**Comment by Aagat** [comment]
Yeah our LDAP is down due to issues with service provider. We're trying to fix it.

**Comment by RyanSquared** [comment]
Fixed, hopefully: [137b704](https://github.com/hashbang/admin-tools/pull/132/commits/137b704f51b77c8da4e19c838b79cedbb4bff8af)
