### ISSUE TITLE
User creation failed

### ISSUE THREAD

**Issue by PRi0NiTY** [hashbang/hashbang.sh#126]
i tried creating a account but it fails

Account creation failed: {
User creation script failed
}

**Comment by RyanSquared** [comment]
When did you try it? We had a hiccup with LDAP last night but it should be working fine now.

**Comment by PRi0NiTY** [comment]
i tried just now

**Comment by RyanSquared** [comment]
We're having minor difficulties right now. Rebooting the server in hopes that it'll fix it.

**Comment by PRi0NiTY** [comment]
oh, my bad

**Comment by RyanSquared** [comment]
Can you try again, and if it fails, provide a full log?

**Comment by PRi0NiTY** [comment]
It works now, no problems here
