### ISSUE TITLE
Account provisioning fails at GPG key verification step

### ISSUE THREAD

**Issue by andrewfluck** [hashbang/hashbang.sh#127]
Some reproduction and other info:
```
OS: macOS Mojave 10.14 DP 3
Account names used in failed attempts:
 - andrew
 - andrewfluck
 - fluck
 - newtsrock
GnuPG PGP version: 2.2.8, built from homebrew
Generated keypair with: ssh-keygen -t rsa -b 2048 -f ~/.ssh/hashbang.sh
```
Errors received:
```
gpg: keyserver receive failed: No route to host

 Downloading key list

gpg: Signature made Tue Feb 14 16:32:16 2017 EST
gpg:                using RSA key 4562BC566932CF1C16F2D7CCD2C4C74D8FAA96F5
gpg: Can't check signature: No public key

Unable to verify keys
```

I do have a public/private keypair in my `~/.ssh` folder, and the bash script recognizes that and proceeds onwards.

I also tried building a `curl` statement as suggested, but that didn't work either.

You are more than welcome to delete the accounts because once this is resolved, I'd like to go back under `andrewfluck` 😀

**Comment by RyanSquared** [comment]
> gpg: keyserver receive failed: No route to host

Which keyserver are we using?

**Comment by RyanSquared** [comment]
actually on further looking, we do use a static one, so it shouldn't have been an issue. the actual issue is that ~~I'm super lazy~~ one or more shell servers is out of date, which I'll hopefully be fixing this weekend.

**Comment by andrewfluck** [comment]
okay, is there any way we can manually create an account now? Or should I just wait for the fix?

**Comment by RyanSquared** [comment]
Well, your account is already created, and you should be able to connect, but it just won't make the dotfiles. For now, you can ssh into da1 or to1 instead of ny1 or sf1

**Comment by andrewfluck** [comment]
I have overwritten my keypair file in case something went, could you delete the other accounts mentioned so I can remake the account?

**Comment by benharri** [comment]
@andrewfluck there's nothing wrong with your keypair. we'll be fixing this up within the next day or so.

**Comment by andrewfluck** [comment]
Oh? I thought if I generate a new one over the old one breaks it because they aren't a pair anymore?

**Comment by andrewfluck** [comment]
Could you delete my accounts anyway?

**Comment by andrewfluck** [comment]
Oh, you are 100% right, there is nothing wrong with the one I had, I forgot I hadn't put the entry in my config file 😂

**Comment by andrewfluck** [comment]
I might just go as `fluck` instead as that account uses my current keypair, the rest can be removed if you want 😛
