### ISSUE TITLE
Unable to connect using a hotspot and getting odd publickey denied issues using my primary internet.

### ISSUE THREAD

**Issue by deceet** [hashbang/hashbang.sh#142]
I just recently signed up for an account and this morning I was connected, but unable to connect to the local irc server. I rebooted thinking it was an error on my end and now I can't connect at all using my primary internet, connection refused, and using my hotspot I'm getting publickey denied messages when trying to connect.

**Comment by RyanSquared** [comment]
We're having network connectivity issues right now regarding a section of IP addresses that we needed to block. This issue will be closed when the network issues are resolved.

**Comment by deceet** [comment]
Thank you for the timely response, I'll just be patient in the meantime. I wasn't sure if it was my end, I use cellular only for inet and it sometimes reports me as coming from different states in the US. Again, much appreciated, hope you get it worked out.

**Comment by benharri** [comment]
We should be back up and running. Feel free to try again!

**Comment by deceet** [comment]
Awesome, all is well from my end. Thanks again!
