### ISSUE TITLE
curl account creation fails

### ISSUE THREAD

**Issue by dannybitgo** [hashbang/hashbang.sh#144]
Wanted to try making an account before auditing the whole script, so was just trying the `curl` method:

```
$ curl -d '{"user":"myuniqueusername", "key":"'"$(cat ~/.ssh/id_rsa.pub)"'","host":"myuniqueusername.hashbang.sh"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
```

But got:
```
{
    "message": "insert or update on table \"passwd\" violates foreign key constraint \"passwd_host_fkey\""
}
```

**Comment by daurnimator** [comment]
You cannot just make up a host, you have to pass a valid hashbang server. For now that's just `de1.hashbang.sh`.

**Comment by dannybitgo** [comment]
> You cannot just make up a host, you have to pass a valid hashbang server. For now that's just `de1.hashbang.sh`.

ohhh thanks! success.
