### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by lrvick** [hashbang/hashbang.sh#15]
Some sort of basic unit testing would be ideal to verify things work as expected at any given time.

Not sure the best way to go about this in bash

**Comment by KellerFuchs** [comment]
Agreed.  However, this should likely use a local install of `shellcheck`.

Speaking of which, I installed it on the shell servers.

**Comment by ChickenNuggers** [comment]
Could we set up Travis CI to install `shellcheck` and then use that to verify everything is POSIX-compliant?

**Comment by KellerFuchs** [comment]
Not sure whether `shellsheck` is a POSIX compliance checker.
In any case, it would make sense to setup whichever CI thing and shellcheck the script (perhaps also check that the webpage is valid HTML and so on?)

**Comment by KellerFuchs** [comment]
Work started in #69

**Comment by ChickenNuggers** [comment]
@KellerFuchs Can we close this?

**Comment by KellerFuchs** [comment]
@ChickenNuggers We still don't have any tests.
What is currently there is a call to a linter (`shellcheck`) and checking the signatures are correct.

**Comment by ChickenNuggers** [comment]
I figured that's all we really needed at that point.

**Comment by lrvick** [comment]
closing this as hashbang.sh is about to just be a static site
