### ISSUE TITLE
Cannot create an account

### ISSUE THREAD

**Issue by genvara** [hashbang/hashbang.sh#152]
I was trying to create an account, but every time i do so it doesn't work, it just comes up with this:

"We are going to create an account with the following information

 Username: genvara
 Public Key: /home/genvara/.ssh/id_rsa.pub
 Host: de1.hashbang.sh

 
 Does this look correct? [Y/n] Y 

 Creating your account...  Account creation failed: {
The browser (or proxy) sent a request that this server could not understand.
}
 
 If you think this is a bug, please report it to 
 -> https://github.com/hashbang/hashbang.sh/issues/
 
 The installer will not continue from here..."

I tried using the curl method and comes up with the same thing, i tried debugging the curl command and it spits out this:
```
[1/3]: "user":"genvara" --> <stdout>
--_curl_--"user":"genvara"
curl: (3) URL using bad/illegal format or missing URL

[2/3]: "key":"(insert rsa key here)" --> <stdout>
--_curl_--"key":"(insert rsa key here)"
curl: (3) URL using bad/illegal format or missing URL

[3/3]: "host":"de1.hashbang.sh" --> <stdout>
--_curl_--"host":"de1.hashbang.sh"
curl: (3) URL using bad/illegal format or missing URL
{
    "message": "The browser (or proxy) sent a request that this server could not understand."
}
```
So yeah... Any help please?

**Comment by daurnimator** [comment]
> I tried using the curl method and comes up with the same thing, i tried debugging the curl command and it spits out this:

hmm?
what happens when you run `curl https://hashbang.sh/server/stats` ?

**Comment by genvara** [comment]
i get this:
```[
    {
        "name": "de1.hashbang.sh",
        "maxusers": 5000,
        "data": null,
        "coordinates": {
            "lat": 49.4478,
            "lon": 11.0683
        }
    }
]
```

**Comment by genvara** [comment]
Hello! so i generated a new ssh key and it worked fine, i wonder why my previous ssh key didn't work, it works fine on everything else...
