### ISSUE TITLE
Is there a way to delete account?

### ISSUE THREAD

**Issue by charmoniumQ** [hashbang/hashbang.sh#155]
Asking for a friend xD

My old harddrive was corrupted and my back up wasn't up-to-date (yeah, I know; it is now...). I don't have access to the old public key. I was wondering if I could get the account deleted and start over.

**Comment by RyanSquared** [comment]
Unfortunately, without any way to prove that you own the account, there's nothing we can do to remove the account. You're more than welcome to start up a new account if you'd like. If you had any way to identify yourself, you can hit us up on IRC and we can discuss account recovery.
