### ISSUE TITLE
Alacritty fail

### ISSUE THREAD

**Issue by 0Karakurt0** [hashbang/hashbang.sh#157]
```
error connecting to /tmp//tmux-13734/default (No such file or directory)
open terminal failed: missing or unsuitable terminal: alacritty
```

just hooped in, don't really know what can be usefull for debugging

**Comment by KellerFuchs** [comment]
@0Karakurt0 This simply means our shell server is missing `terminfo` metadata for your specific terminal.

You can work around the issue by changing the `TERM` environment variable to another, compatible and widely-supported terminal.  For instance, `TERM=xterm ssh de1.hashbang.sh` should work for you
