### ISSUE TITLE
Duplicate account due to script crash

### ISSUE THREAD

**Issue by ghost** [hashbang/hashbang.sh#160]
I tried setting up an account under the uname thomasc. The gpg key's wouldn't download during the setup causing the script to crash while trying to verify with nothing to verify with. I fixed the issue involving the keyserver and my router taking over my dns, but it looks like the account was partially setup. I deleted and regenerated the keypair thinking I needed to set an ssh key passphrase to auth, but Due to the named issues the user thomasc needs to be deleted as it isn't accessable.

**Comment by RyanSquared** [comment]
Deleted since it appears no one ever connected under that name but according to userdb the account did create itself 100% fine.
