### ISSUE TITLE
Can't create account (Can't verify hashbang GPG key)

### ISSUE THREAD

**Issue by shitwolfymakes** [hashbang/hashbang.sh#163]
If I run the script, I get all they way through until the verification of the GPG key, where I get:

`gpg: keyserver receive failed: Server indicated a failure`

Also, the only available server is `de1`? Is this still alive?

**Comment by RyanSquared** [comment]
You can try using `--keyserver keyserver.ubuntu.com` with gpg to change the keyserver it connects to. I believe MIT is still the default in some places but it fails quite often.

de1 is currently the only available server, and still has capacity for more users.

**Comment by shitwolfymakes** [comment]
Thanks! I'll give this a try

**Comment by RyanSquared** [comment]
If you are having issues creating an account, I believe an account may have already been created. It looks like the step you reached was getting the known_hosts file.

**Comment by shitwolfymakes** [comment]
That worked! I got a gpg warning that the "key is not certified with a trusted signature!", but over than that everything looks good, thanks!
