### ISSUE TITLE
Unable to establish ssh; new user

### ISSUE THREAD

**Issue by khanzardar** [hashbang/hashbang.sh#176]
- I ran the installation script, went through the steps, choose a username, server, location for key etc.
- however when I run `ssh hashbang.sh or ssh zardar@hashbang.sh` I run into the following error, any pointers will be greatly appreciated:

```ssh zardar@hashbang.sh
Enter passphrase for key 'id_ed25519': 

Error: Unable to get host list
Get "https://userdb.hashbang.sh/v1/hosts": read tcp 10.244.1.146:58630->174.138.102.152:443: read: connection reset by peer
Connection to hashbang.sh closed.```

**Comment by RyanSquared** [comment]
congrats on finding our in-dev user management server! I think you meant to connect with `ssh zardar@de1.hashbang.sh`, which will connect you to your home server.

**Comment by khanzardar** [comment]
Hey @RyanSquared, thanks for the welcome and help. I should specified that I tried with hostname included `zardar@de1.hashbang.sh` as well. There must've been an issue on my local during setup. I tried to walk through the same installation steps and was able to create another account `khanz` and login successfully
