### ISSUE TITLE
User creation failed

### ISSUE THREAD

**Issue by fmattheus** [hashbang/hashbang.sh#18]
Hello, I tried to create a user with the manual script:
`curl -d '{"user":"fmattheus","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create`
But it fails with:
`{"message": "User creation script failed"}%`

**Comment by necrophcodr** [comment]
Do you have an SSH key at that location?

If you run

    # echo '{"user":"fmattheus","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}'

Does it print the above, with your SSH public key?

**Comment by fmattheus** [comment]
Yes I do, here is the output of your echo, I replaced the public key with xxx ...

`{"user":"fmattheus","key":"ssh-rsa xxx frank@machinename"}`

**Comment by daurnimator** [comment]
> I replaced the public key with xxx ...

btw, a public key is public. no need to hide it ;)

**Comment by lrvick** [comment]
Please provide full command including public key so we can debug

**Comment by PrinceOfEgypt** [comment]
I am also seeing the same error. here is the output of the echo for me:

{"user":"abdelmalek", "key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGrgEmCvoVRqjpUUDXKD591GqQCPBGXR8IF2mmth4VHi/Wz4mzMmPUN4b7vFDLOqzg9lIZU3pAfihwNSvHHs1tnaL6MvfLR+9XRMRnygzO3oO60Vlr8ly1vmCYzfZufhkZ8va10wSiOVT9woZpd3P0ABPw09VAsl4mSjjTSKlm1EWigLwHhOT3B88+RcsKJxIjkjChOIPVds65sAElXU1hockq4F290kw5teieN41a0HVPhscREXgxtpvhkAtrw0f0zoUCLPQtd8az5jLIuXt21heiO2ANTfSpWkBDESNODY5llOlTHlBGoAsUMszFI5oBahHixVu/DOYJFgAMOYxX abdelmalek@athlon"}

**Comment by lrvick** [comment]
Try removing the comment in the ssh key. (If that works, it is still a bug,
but want to confirm what is what it is)

On Mon, Mar 16, 2015 at 11:20 AM, PrinceOfEgypt <notifications@github.com>
wrote:

> I am also seeing the same error. here is the output of the echo for me:
>
> {"user":"abdelmalek", "key":"ssh-rsa
> AAAAB3NzaC1yc2EAAAADAQABAAABAQDGrgEmCvoVRqjpUUDXKD591GqQCPBGXR8IF2mmth4VHi/Wz4mzMmPUN4b7vFDLOqzg9lIZU3pAfihwNSvHHs1tnaL6MvfLR+9XRMRnygzO3oO60Vlr8ly1vmCYzfZufhkZ8va10wSiOVT9woZpd3P0ABPw09VAsl4mSjjTSKlm1EWigLwHhOT3B88+RcsKJxIjkjChOIPVds65sAElXU1hockq4F290kw5teieN41a0HVPhscREXgxtpvhkAtrw0f0zoUCLPQtd8az5jLIuXt21heiO2ANTfSpWkBDESNODY5llOlTHlBGoAsUMszFI5oBahHixVu/DOYJFgAMOYxX
> abdelmalek@athlon"}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/hashbang.sh/issues/18#issuecomment-81852074>.
>



-- 
Lance R. Vick
__________________________________________________
Cell      -  407.283.7596
Gtalk     -  lance@lrvick.net
Website   -  http://lrvick.net
PGP Key   -  http://lrvick.net/0x36C8AAA9.asc
keyserver -  subkeys.pgp.net
__________________________________________________

**Comment by fmattheus** [comment]
Unfortunately, removing the comment doesn't change anything.  Still get
"User creation script failed".

>

**Comment by fmattheus** [comment]
Today it works.  Thanks for the fix on the server side
