### ISSUE TITLE
user provisioning API is not straightforward

### ISSUE THREAD

**Issue by Veraellyunjie** [hashbang/hashbang.sh#184]
> As an advanced alternative you can bypass using this script and hit our user provisioning API directly with an SSH Public Key and desired username:

```
> curl -d '{"user":"v11e","key":"'"$(cat ~/.ssh/v11e@hashbang.sh.pub)"'","host":"de1.hashbang.sh"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
{
    "message": "success"
}
```
Seems good... Try logging in:
```
> ssh -i ~/.ssh/v11e@hashbang.sh v11e@hashbang.sh
Enter passphrase for key '/home/v11e/.ssh/v11e@hashbang.sh': 

Error: Unable to get host list
Get "https://userdb.hashbang.sh/v1/hosts": read tcp 10.244.1.204:48446->174.138.102.152:443: read: connection reset by peer
Connection to hashbang.sh closed.
```
Pluck the URL manually:
```
> curl https://userdb.hashbang.sh/v1/hosts
[{"name":"de1.hashbang.sh","maxusers":7500,"data":null}]
```
Seems OK, but again no:
```
> ssh -i ~/.ssh/v11e@hashbang.sh v11e@hashbang.sh
Enter passphrase for key '/home/v11e/.ssh/v11e@hashbang.sh': 

Error: Unable to get host list
Get "https://userdb.hashbang.sh/v1/hosts": read tcp 10.244.1.204:57054->174.138.102.152:443: read: connection reset by peer
Connection to hashbang.sh closed.
```
Maybe the `de1` will make a difference:
```
> ssh -i ~/.ssh/v11e@hashbang.sh v11e@de1.hashbang.sh
The authenticity of host 'de1.hashbang.sh (46.4.114.111)' can't be established.
Welcome to #!
```
Indeed. Me fool, I did specify `de1.hashbang.sh` at the 1st command to register, how would I expect it to connect via `hashbang.sh`! But wait, it says "Your Hashbang email address is ... hashbang.sh" - without `de1`.

Confusing, may I say... :)

**Comment by RyanSquared** [comment]
Usernames are not restricted to a single server, which is why mail is run from `@hashbang.sh`. The server you've configured as your host is the server your mail will be delivered to (via Maildir). We do not run a proxy through `hashbang.sh` and I don't think we ever advertise `ssh hashbang.sh` - if we do, it's a bug, blame @lrvick
