### ISSUE TITLE
User creation error

### ISSUE THREAD

**Issue by Blacksim** [hashbang/hashbang.sh#20]
Problem to create a new account with all 3 ways used .
user: **b72simon**
public key stored in **`~/.ssh/id_rsa.pub`** and created during script process
```json
{"user":"b72simon","key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiXmmxVK5iIDx6pk23eRwJX78/6trmcn5FhjtYM103u52S9N8RngYTUGKcDKwHSgAuhiIq7yc+mqffgoj597LzraU6BXI04Gh6XU7fXuWLu+5KoDvsJS1bmmCKVPmezY2dEh6G1v4LM1sMx54JAFDRbWFVlU8yjubiqQJlzqu51fE284In0JiBz9gycjaFELGSSLLBmoMvqus8wKALH7dt02fw8AjzLkrFZnZq+etT+YsTbguGdemC833/ZGNGk06ekLcNVrNA5VDM0cptwOj9hu84gAPFDjcEs6ox5Pi6sFzn0zDcndojdQ6k04JIPAWF5w3FP+3zjFVCm8DQYlJZ #! b72simon"}
```
1: **`$ ./hashbang.sh`**
error >>> `curl: (22) The requested URL returned error: 400 BAD REQUEST`

2: **`$ curl -d '{"user":"b72simon","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create`**
error >>> `{"message": "User creation script failed"}`

3 **`$ curl -H "Content-Type: application/json" -d "{\"user\":\"b72simon\",\"key\":\"$(cat ~/.ssh/id_rsa.pub)\",\"host\":\"va1\"}" https://hashbang.sh/user/create`**
error >>> `{"message": "User creation script failed"}`

where is the problem?

**Comment by daurnimator** [comment]
> where is the problem?

> +3zjFVCm8DQYlJZ #! b72simon"}

I think it's intepreting the `#` in your id_rsa.pub as the start of a comment.

**Comment by daurnimator** [comment]
Can you try:
```
curl -d '{"user":"b72simon","key":"'"$(cat ~/.ssh/id_rsa.pub | awk '{ print $1 " " $2 }')"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
```

**Comment by Blacksim** [comment]
SOLVED !!! 
{"message": "success"}

Thank you for support.

**Comment by mvillarejo** [comment]
I'm receiving a similar error, 400 while creating the account:
`curl: (22) The requested URL returned error: 400`
tried to do the curl with: 
```
$ cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9pVhoMFIvBY7g4iicWNe6cA3WR+NWJDAlzwQTijJuUvHQqpYWpYK1fZFD/ue3vCW0u6w94m+F0nqZWY7JVJCdHZbnrJdKHsVKNjYyKB8LFOrcwbyt1Pot1aMvaM8ERvEFlB4a9E5Fgr22+
Gf5ndsKOMBjTt4vgdPSOEJXc1LtWwC3/k7cOgQc69AMZM6pfa5MjAYP+UaKsjuEAm+5b+0wvyJLexpMMOToHgIFk2ZYRlM3g5nWDuXYqkGki4kgSOnKfELhMG2ro9MymZ6k8hrzv1faAJoc8YCYZco1K2G4T77oEkKdY2Gpf7Z/iC7i0E7NVH
ERnM9tGQ8ZOqvDqmlR
```

but no luck, any ideas?
