### ISSUE TITLE
Tab Shell closed by mistake

### ISSUE THREAD

**Issue by Blacksim** [hashbang/hashbang.sh#21]
After the SSH connection with the server **b72simon@va1.hashbang.sh** (b72simon is my username) I've inadvertently closed my remote shell with the **exit** command. 
Now I can only move between the tab 1:chat and tab 2:email. Tab 3:shell no longer exists.

Any suggestion?
Thank you

**Comment by necrophcodr** [comment]
Press "CTRL+C".

**Comment by jhass** [comment]
Almost, it's Ctrl+B then C ;)

**Comment by Aagat** [comment]
#! shells have tmux by default, so this might be of further help.

https://gist.github.com/MohamedAlaa/2961058

Welcome to #!

**Comment by Blacksim** [comment]
SOLVED
Ctrl+B, release and then C

Thank you all for help
