### ISSUE TITLE
User creation error

### ISSUE THREAD

**Issue by lupettohf** [hashbang/hashbang.sh#22]
```
~/Desktop❯ curl -d '{"user":"lupetto","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
{"message": "User creation script failed"}%  

~/Desktop❯ echo '{"user":"lupetto","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}'
{"user":"lupetto","key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9X1LQ3YPPdC5aFekgKejDWid/PGYQkj6Hg8cVn82z3GxA/0yp7hFubr/PVpDVVn01cJJlrgfQ1iktRIo4fvqXZTsDATZZx7n7rpASDeY43ZJjhQhGWKDMRsSnWPkMtFk8Dm1ZnF1/yiUX+4ywA+8GXrZzugJ2RKSQTHXA62MNpUvhuoCbWy9gyIvcqh6IHXhMXGPDuEtHzhP2RYROwVKzPRj5/gOTJ7+L+PoQfiwg3yAKzevnEq5FdWYsgoPytCNnStiYhFZOuN8fn3Ujbfx9HhOC/8Rd/KgqaQae0YZ4LPzGUT7EiGp4QZMIVbKlP5Ong3N7CgpbKoAhVjqpRZ63 OpenShift-Key"}

**Comment by Blacksim** [comment]
take a look at the closed #20 issue. I solved the problem.

**Comment by lupettohf** [comment]
@Blacksim 
~❯ curl -d '{"user":"lupetto","key":"'"$(cat ~/.ssh/id_rsa.pub | awk '{ print $1 " " $2 }')"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
{"message": "User creation script failed"}

**Comment by Blacksim** [comment]
Manually remove in the file id_rsa.pub the final **OpenShift-Key**
Then try again. What happen ?

**Comment by lupettohf** [comment]
Nothing :/

**Comment by jhass** [comment]
@lupettohf we an issue with the sign up server, can you please try again now?

**Comment by roseswe** [comment]
Same here, I get:
{"message": "[key]: Expected 'ssh-rsa', 'ssh-dsa', or 'ssh-ecdsa'"}

My keys:
~/.ssh > cat *.pub|awk '{ print $1  }'
ssh-dss
ecdsa-sha2-nistp521
ssh-rsa

ssh-rsa works then......

**Comment by jhass** [comment]
@roseswe would you mind opening a separate issue about supporting `ecdsa-sha2-nistp521` and `ssh-dss`? In the mean time you should be able to select the rsa key manually with the command in the [comment above](https://github.com/hashbang/hashbang.sh/issues/22#issuecomment-82582471).

**Comment by roseswe** [comment]
->  Support for non RSA keys #24 
ok2close #22 from my side :-)
