### ISSUE TITLE
User creation script failed

### ISSUE THREAD

**Issue by tkossak** [hashbang/hashbang.sh#23]
I run

    curl -d '{"user":"kossak","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create

and get the error

    {"message": "User creation script failed"}

My ```~/.ssh/id_rsa.pub``` file (there's not "#" char in it):

    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+bp/jb/2vVAMd/leiloPQAYzYyVhEghD8kugiYkjvlJclvIYuGhDjV+Ju17uvk1pf5/w86wYUsqCKpDa/hu8BMjfx7xwI5kShYZ6XePXdKS7uGrXKpEf8E+dFmC3ve+GqtIxYSolYH8vqxPbpcLCQehP9OUjqLrSMziTSK4wenMn1Di2PXwMnSUvrMomZH9jugYAlL8zCfQsyNtXhsWGvDf0Vo/VMrAPSGUGGhufaV9J7/oV8u1yYPDOJK1wKjaBFAwBUJXBEpWG+2yFiW3BEh1Uf1MGoAzt2mCfyOVlVv3qQjTuFGJ5EL5YPQNAyrsGC88LxEjLr/7Z5kBeJkbudUfdplSKZhQCIbVpa3TNy7EKENMgdJGaRU99JYxNsvZDfkLQjCvk1GMNZbN350gk7h1I3V/KZEeijvzapbxSdpyDhy+BM8oNZI2SAXEeV6FfTT2mlKZjepcMbeQGnGmGbeLMuTm78lYkkgZvRi/tEZgltyG9/Yqj/+PhXTYjDkfm9Yo6QHagm4E+N0dFglbzttDHsI2F4TVdbzpbDhQolJfRkMv5Fk4j8vOQKsejPSSla2heXcDQ7zLrGFc/W2JxNZrXHP/4m3Q36X09L+kdD1ZfbZ7i02AGO/gJUTvIKOclNXP8dNbiKjzl7ZF1dNV6gwr2CVquBE0AerJV1NnE7vQ== kossak@LMQ

It also doesn't work with the default sh script.

**Comment by daurnimator** [comment]
If you put an `echo` in from of the `curl` command, what do you see?

**Comment by tkossak** [comment]
curl -d {"user":"kossak","key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+bp/jb/2vVAMd/leiloPQAYzYyVhEghD8kugiYkjvlJclvIYuGhDjV+Ju17uvk1pf5/w86wYUsqCKpDa/hu8BMjfx7xwI5kShYZ6XePXdKS7uGrXKpEf8E+dFmC3ve+GqtIxYSolYH8vqxPbpcLCQehP9OUjqLrSMziTSK4wenMn1Di2PXwMnSUvrMomZH9jugYAlL8zCfQsyNtXhsWGvDf0Vo/VMrAPSGUGGhufaV9J7/oV8u1yYPDOJK1wKjaBFAwBUJXBEpWG+2yFiW3BEh1Uf1MGoAzt2mCfyOVlVv3qQjTuFGJ5EL5YPQNAyrsGC88LxEjLr/7Z5kBeJkbudUfdplSKZhQCIbVpa3TNy7EKENMgdJGaRU99JYxNsvZDfkLQjCvk1GMNZbN350gk7h1I3V/KZEeijvzapbxSdpyDhy+BM8oNZI2SAXEeV6FfTT2mlKZjepcMbeQGnGmGbeLMuTm78lYkkgZvRi/tEZgltyG9/Yqj/+PhXTYjDkfm9Yo6QHagm4E+N0dFglbzttDHsI2F4TVdbzpbDhQolJfRkMv5Fk4j8vOQKsejPSSla2heXcDQ7zLrGFc/W2JxNZrXHP/4m3Q36X09L+kdD1ZfbZ7i02AGO/gJUTvIKOclNXP8dNbiKjzl7ZF1dNV6gwr2CVquBE0AerJV1NnE7vQ== kossak@LMQ"} -H Content-Type: application/json https://hashbang.sh/user/create

**Comment by daurnimator** [comment]
Can you try it with the `awk` as in this issue: https://github.com/hashbang/hashbang.sh/issues/20#issuecomment-81932088

I'm wondering if the @ is throwing curl off

**Comment by Blacksim** [comment]
Manually remove in the file id_rsa.pub the final **kossak@LMQ**
Then try again. What happen ?

**Comment by tkossak** [comment]
no luck:

    curl -d '{"user":"kossak","key":"'"$(cat ~/.ssh/id_rsa.pub | awk '{ print $1 " " $2 }')"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create

gives the same error.

After removing kossak@LMQ from ```id_rsa.pub```: the same error with both version of curl (with awk and without).

    curl -d '{"user":"kossak","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create

witch echo on the begining:

    curl -d {"user":"kossak","key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+bp/jb/2vVAMd/leiloPQAYzYyVhEghD8kugiYkjvlJclvIYuGhDjV+Ju17uvk1pf5/w86wYUsqCKpDa/hu8BMjfx7xwI5kShYZ6XePXdKS7uGrXKpEf8E+dFmC3ve+GqtIxYSolYH8vqxPbpcLCQehP9OUjqLrSMziTSK4wenMn1Di2PXwMnSUvrMomZH9jugYAlL8zCfQsyNtXhsWGvDf0Vo/VMrAPSGUGGhufaV9J7/oV8u1yYPDOJK1wKjaBFAwBUJXBEpWG+2yFiW3BEh1Uf1MGoAzt2mCfyOVlVv3qQjTuFGJ5EL5YPQNAyrsGC88LxEjLr/7Z5kBeJkbudUfdplSKZhQCIbVpa3TNy7EKENMgdJGaRU99JYxNsvZDfkLQjCvk1GMNZbN350gk7h1I3V/KZEeijvzapbxSdpyDhy+BM8oNZI2SAXEeV6FfTT2mlKZjepcMbeQGnGmGbeLMuTm78lYkkgZvRi/tEZgltyG9/Yqj/+PhXTYjDkfm9Yo6QHagm4E+N0dFglbzttDHsI2F4TVdbzpbDhQolJfRkMv5Fk4j8vOQKsejPSSla2heXcDQ7zLrGFc/W2JxNZrXHP/4m3Q36X09L+kdD1ZfbZ7i02AGO/gJUTvIKOclNXP8dNbiKjzl7ZF1dNV6gwr2CVquBE0AerJV1NnE7vQ== "} -H Content-Type: application/json https://hashbang.sh/user/create

And it gives the same error (removing space at the end doesn't help either, and removing "==" returns another error - bad base64 encoding)

**Comment by jhass** [comment]
@tkossak we an issue with the sign up server, can you please try again now?

**Comment by tkossak** [comment]
Still doesn't work (tried sh script, curl and curl with awk), same error.

**Comment by jhass** [comment]
@tkossak okay, looks like it needed a final restart. Thanks for your patience and please try again.

**Comment by tkossak** [comment]
Works, awesome, thank you. Now it's time to sleep though, good night :)
