### ISSUE TITLE
Support for non RSA keys

### ISSUE THREAD

**Issue by roseswe** [hashbang/hashbang.sh#24]
When trying to use non RSA keys:
{"message": "[key]: Expected 'ssh-rsa', 'ssh-dsa', or 'ssh-ecdsa'"}

~/.ssh > cat *.pub|awk '{ print $1 }'
ssh-dss
ecdsa-sha2-nistp521
ssh-rsa

**Comment by l29ah** [comment]
{"message": "[key]: Expected length to be between 192 and 8192 characters"}
‰ wc ~/.ssh/id_ed25519.pub
 1  3 97 /home/l29ah/.ssh/id_ed25519.pub

**Comment by lrvick** [comment]
This appears to be misfiled, and should be on provisor. The related bit of code for this is here: 
https://github.com/hashbang/provisor/blob/master/provisor/utils.py#L44-L57

Please feel free to submit a PR or issue there. It should be pretty straight forward to modify to include whatever you like, and we will happily deploy it.

**Comment by ChickenNuggers** [comment]
[#10](https://github.com/hashbang/provisor/issues/10) closed, closing.
