### ISSUE TITLE
error creating account

### ISSUE THREAD

**Issue by ksaver** [hashbang/hashbang.sh#26]
The hashbang,sh script is not creating account correctly, it show this error:
--- 
We are going to create an account with the following information
 
 Username: my_username
 Public Key: ~/.ssh/id_rsa.pub
 Host: va1
 
 Does this look correct? [Y/n] y
 
 Creating your account...
 
curl: (22) The requested URL returned error: 400
 
 Account creation failed.
 Something went awfully wrong and we couldn't create an account for you.
 If you think this is a bug, please report it to 
 -> https://github.com/hashbang/hashbang.sh/issues/
 
 The installer will not continue from here...

---
Using the API  is not working for me also...

curl -d '{"user":"my_username","key":"'"$(cat ~/.ssh/id_rsa.pub)"'"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create   
{"message": "User creation script failed"}%

**Comment by Flashwalker** [comment]
Same for me.

**Comment by lrvick** [comment]
Try now. Server was in a bad state and needed to be restarted.

**Comment by lrvick** [comment]
Just implemented support for automatic re-connection which should hopefully solve this for good.

**Comment by lrvick** [comment]
Considering I saw you connect successfully, I am closing this.

**Comment by ksaver** [comment]
Yes, thank you very much! :)

**Comment by dongalor** [comment]
looks like the same issue, am I right? :)

**Comment by lrvick** [comment]
fixed

On Wed, Apr 8, 2015 at 5:21 AM, Paul <notifications@github.com> wrote:

> looks like the same issue, am I right? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/hashbang.sh/issues/26#issuecomment-90858779>.
>



-- 
Lance R. Vick
__________________________________________________
Cell      -  407.283.7596
Gtalk     -  lance@lrvick.net
Website   -  http://lrvick.net
PGP Key   -  http://lrvick.net/0x36C8AAA9.asc
keyserver -  subkeys.pgp.net
__________________________________________________
