### ISSUE TITLE
Permission problem on ~/.ssh/config

### ISSUE THREAD

**Issue by bob109** [hashbang/hashbang.sh#27]
I did not have a ~/.ssh/config file so I let hashbang.sh create one for me. It created it with permissions 664. which is the default with a 0002 umask.

When trying to connect I got the message

>Bad owner or permissions on /home/bob/.ssh/config

I looked up the error and found that the file should have 600 just like a ssh private key.  I did a chmod 600 ~/.ssh/config and it's all good now.. 

The portion of the script is here

> 360        if ask " Would you like an alias (shortcut) added to your .ssh/config?" Y ; then
> 361            printf "\nHost hashbang\n  HostName ${host}.hashbang.sh\n  User %s\n  IdentityFile %s\n" \
> 362							"$username" "$keyfile" \
> 363            >> ~/.ssh/config
> 364           echo " You can now connect any time by entering the command:";

On my copy I inserted the following between 360 and 361.and it seems to have done the trick.

> if [ ! -f ~/.ssh/config ] ; then
>   touch ~/.ssh/config 
>   chmod 600 ~/.ssh/config
> fi

bob

**Comment by AlissaSquared** [comment]
I believe I have resolved this issue and will close when the commit is merged.

**Comment by ChickenNuggers** [comment]
Resolved, I believe. Keys are also chmodded 600.
