### ISSUE TITLE
Missing trust link

### ISSUE THREAD

**Issue by mwgamera** [hashbang/hashbang.sh#29]
I think that the script (which is signed with GPG and served over HTTPS) should contain SSH fingerprints. It could either just echo them for user to compare, or even better (more evil!) — it could contain full keys and simply stuff them into user's ~/.ssh/known_hosts. (Given that user already trusts the script, and that the script already assumes OpenSSH, I think the latter would be right thing to do.)
You may think that this is pointless but consider what value has a warrant canary signed with GPG when user could just be MTIM-ed all the time without any possibility of checking if the SSH server they connect to is indeed under the control of the one who holds the GPG key.

**Comment by lrvick** [comment]
This is a very fair point. I like the known_hosts idea.

PR for that would be welcome.

**Comment by necrophcodr** [comment]
If the known_hosts thing is going to happen, ensure that it is

 * Stuffed into the file correctly, on all platforms. Obviously.
 * Accepted. The user MUST agree on this to happen.

Other than that, it sounds pretty reasonable to do this, and to let the user review the SSH fingerprints too. Very good point, especially if the server ONLY accepts HTTPS (otherwise it kind of renders the point moot).

**Comment by lrvick** [comment]
Resolved via patch:  https://github.com/hashbang/hashbang.sh/pull/30

**Comment by mwgamera** [comment]
The existence of a file containing SSH keys and signed with PGP (as #30 expects to find under `https://hashbang.sh/static/known_hosts.asc`) should be sufficient to establish the link between the two keys and indeed solves this issue.

Such file could be manually verified that it is signed with the same key as the script. #30 attempted to do this automatically, but it's hard to do right and I think it should be avoided. There's a good reason that I wrote it's an _evil_ idea. Evil as in easy to make things worse than they are. Tough, I thought about the act adding it to `konwn_hosts` itself and didn't even consider problems of verification.

What I had in mind when I opened this issue was leveraging the implicit trust that user has put in the script by running it, and putting all the relevant data directly in it. User hopefully already verified the signature before running the script so they know the association (this doesn't help them verifying if the script is okay to run, but it does help establishing that the one who signed it, also signed the canary and whatever other data is included in it). Putting the keys or key fingerprints directly into script is the same as having a separate file signed with the same key, except you don't need to separately fetch and verify it. Verifying PGP signatures is non-trivial to do and I would try to avoid it had I written the patch.

My original idea was using something as simple (and easy to understand, and to verify it's correct and secure) as:
```sh
cat << END >> ~/.ssh/known_hosts
va1.hashbang.sh ssh-rsa (...)
(...)
END
```
Perhaps additionally grepping by `$host`.

But there are many other simple ways of doing it, none of which involves calling gpg.
For example, the script could contain just a cryptographically secure hash like SHA256 of another file that could be fetched and checked it matches the hash. Just a hash, in a signed and implicitly trusted script, rather than a separate signature.

#30 initially used `ssh-keyscan` to fetch keys from SSH server, and I think this was another interesting idea, especially for RSA keys which are quite long. Of course it can not be treated as trusted and must be verified before being put into `known_hosts` but the signed script could contain only fingerprints and verify that fetched keys match them (I think this would require using temporary file, though). Having fingerprints inside the script has additional benefit of being easy to check manually for those who decide to skip adding keys to `known_hosts`.

OTOH, having separate file with absolutely separate signature has an advantage of being possible to update without touching the script. But I don't think this is that big of an advantage given that this script is already assembled from two files before being singed and adding some additional data shouldn't be a big problem.
