### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by geoffmcc** [hashbang/hashbang.sh#36]
So, I have been having issues. First account I created I did not also put a password for the key. This would not allow me to log on. I since made another account, this time giving a password for the key, it connects the first time, but then when I try to connect again, i get to the password prompt and it will no longer accept my connection.

I feel like an idiot for making so many accounts, not sure if these can be reset or not

geoffmcc, geoffmcc123, ersatz & geoffm

**Comment by AlissaSquared** [comment]
The accounts can probably easily be reset with no problem. Do you mind sharing with us the text that was outputted from the SSH connection? Did it just randomly exit?

**Comment by geoffmcc** [comment]
well on the first attempt that I was actually able to get connected (geoffmcc123) when asked if I want to log in as part of the script, I say yes and it logs me in. After I log out, I cannot get in again. I was given a message about no access (pubkey).

I did some searching and found may be a permission prblem on the file so I tried 600 and 400. Both optons ask for the password that I signed key with, but it will not accept .... again, this was after I was on and disconnected (so it accepted the password the first time).

WIll these accounts that I made eventually get dropped, dont want to have a bunch of accounts.

**Comment by lrvick** [comment]
what exact ssh command are you running? A lot of people forget it is {server}.hashbang.sh, and for most people that means va1.hashbang.sh right now.

**Comment by geoffmcc** [comment]
sorry for the delay. I am using the alias configured by install script. I see when i ssh -vvv hashbang and then enter the password for the key, I get 

https://gist.github.com/geoffmcc/90babf1947dfd81e7fa5

I know it says bad password, but I am 100% sure that it is not.

**Comment by lrvick** [comment]
That is the encryption password you set when you created your key. For
whatever reason it is not what you expect, and we can't reset it as it only
exists on your computer. If you are locked out of your key, you will have
to generate a new one using 'ssh-keygen' then send us your new public key
and we can point your account to your new key.

On Thu, Apr 23, 2015 at 5:49 PM, Geoffrey McClinsey <
notifications@github.com> wrote:

> sorry for the delay. I am using the alias configured by install script. I
> see when i ssh -vvv hashbang and then enter the password for the key, I get
>
> https://gist.github.com/geoffmcc/90babf1947dfd81e7fa5
>
> I know it says bad password, but I am 100% sure that it is not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/hashbang.sh/issues/36#issuecomment-95764317>.
>



-- 
Lance R. Vick
__________________________________________________
Cell      -  407.283.7596
Gtalk     -  lance@lrvick.net
Website   -  http://lrvick.net
PGP Key   -  http://lrvick.net/0x36C8AAA9.asc
keyserver -  subkeys.pgp.net
__________________________________________________

**Comment by AlissaSquared** [comment]
As of the current hosted script on https://hashbang.sh, please note that while viewing the source, the script assumes that the key is ~/.ssh/id_rsa.pub or something as such if you generate your own key. If you generated a key during registration that wasn't id_rsa.pub, you need to use the id_rsa as of current to connect to hashbang.

**Comment by geoffmcc** [comment]
thanks for the help, I am in now. The alias created by installer referenced id_rsa.pub. I changed that in config (.ssh) to id_rsa and i am now able to connect. I know have multiple accounts. Will the ones I am not using eventually purge?

**Comment by AlissaSquared** [comment]
If you give us the names we'll likely be able to purge them. And thanks for the note about that. I think that's one of the issues my fork fixed.

If you still need to talk with us, in the server's tmux session window 1 (ctrl + b, then 1), you'll be able to talk with us there.

**Comment by geoffmcc** [comment]
ok. so trying to get this to work, I think i setup

geoffmcc, geoffmcc123, ersatz 

sorry to create so much, the first one I thought it didnt like that i opted not to use password on key, cause it kept saying wrong password so I created the second account. Second account had same issue. 

Not to be a pain, but if we can get those purged, along with my working gmcclins I would like to go back to geoffmcc, but if not I can deal with what I have
