### ISSUE TITLE
Problem in IdentityFile when setting alias

### ISSUE THREAD

**Issue by leowzukw** [hashbang/hashbang.sh#37]
By default, when the script creates the alias for hashbang in ```~/.ssh/config```, it sets the pub key for authentification. When the user tries to connect, a password is asked and it can't work since the pubkey don't have any password.

I solved the problem manualy and I could connect.

config before
```
  IdentityFile /home/lwzukw/.ssh/hashbang.pub
```

config after
```
  IdentityFile /home/lwzukw/.ssh/hashbang
```

**Comment by lrvick** [comment]
I think this is already solved by https://github.com/hashbang/hashbang.sh/pull/31 which is pending testing/merging atm

**Comment by lrvick** [comment]
@AlissaSquared ^

**Comment by AlissaSquared** [comment]
https://github.com/hashbang/hashbang.sh/commit/c50a95dae9082d0a7bdf2eca18ce6884dc999631#diff-66047bc80b7362394dce1377b4bf520eR170 Fixed. Up a few lines you'll see the broken version.
The new patch that I have written expects the user to write out the private key, then appends ".pub" to the key when using 'cat' to post it to the server.
I'll put a notice in the script later to mention that.

**Comment by leowzukw** [comment]
Great!

**Comment by AlissaSquared** [comment]
Issue will be closed when merged.

**Comment by AlissaSquared** [comment]
Testing should be done somewhat close in the future.

**Comment by ChickenNuggers** [comment]
Fixed. Merged. Live and working.
