### ISSUE TITLE
Supposed ~/.ssh/config problem

### ISSUE THREAD

**Issue by AlissaSquared** [hashbang/hashbang.sh#40]
Error on user generation claimed on IRC where host was sfo1.hashbang.sh.hashbang.sh. Needs confirmation. I might look at this later myself if it's unsolved when I get home.

**Comment by AlissaSquared** [comment]
https://github.com/hashbang/hashbang.sh/commit/375198e5a4d40bda68fbc068211c21f6a4aa9043 - Supposedly fixed. Will close when commit is live.

**Comment by nchase** [comment]
:clap:
