### ISSUE TITLE
hashbang.sh is not in compliance with POSIX

### ISSUE THREAD

**Issue by necrophcodr** [hashbang/hashbang.sh#43]
It appears that hashbang.sh is not in compliance with POSIX as stated in the beginning of the file. This is due to various bashisms, and what not, that is not specified in POSIX, nor as POSIX extensions.

**Comment by lrvick** [comment]
Yeah I know we were compliant at one point but we had to make a ton of changes. If you can adapt said changes like you did last time that would be awesome.

**Comment by necrophcodr** [comment]
I don't find it acceptable, so I'm working on it. It's going to be a lot of work though, and I have a couple of other projects due last weekend, so I'll do what I can. No promises. I've already made a pull request, so you guys can work through that for now and decide how much it's worth, and what else should be changed. After all, it's a relatively simple shell script :+1:

**Comment by ChickenNuggers** [comment]
Is there a status on this? I'll look for a POSIX compliancy testing service later.

**Comment by ChickenNuggers** [comment]
Looking through some things now, I believe that testing everything with `bash`, `zsh`, and `posh` would be the best way - making sure it's compatible with two of the most common shells and the "Posix Ordinary Shell" sounds reasonable enough. Should we add this to the contributing guidelines?

**Comment by KellerFuchs** [comment]
We could also test it against `dash`, as it is Debian's default `sh` (and a fairly bare-bones one).

**Comment by necrophcodr** [comment]
You'd also need busybox ash, which is the default in Alpine Linux and SliTaz and other distributions.

There's a few variations, but mostly it should just work if you stick to the POSIX standard.

Some shells won't ever work though, because they're retarded.

**Comment by ChickenNuggers** [comment]
`dash` is a direct port of `ash` to Linux. Should we really need to test it?

> Some shells won't ever work though, because they're retarded.

Looking at you, `fish`.

**Comment by KellerFuchs** [comment]
> There's a few variations, but mostly it should just work if you stick to the POSIX standard.
The point is that we should only rely on having a POSIX shell, and testing on a variety of shells that implement a small superset of the POSIX requirements (or strictly POSIX) should help us check that.

> Some shells won't ever work though, because they're retarded.
I doubt we want to (or reasonably can) support non-POSIX shells maskerading as `/bin/sh`.

**Comment by necrophcodr** [comment]
I've taken a look at the code again, and it seems to be mostly up to par, with a few hits and misses. I'll do what I can to make these changes public soon.

On another note, could someone delete my user from the ny1.hashbang.sh server? I don't have the SSH key for that one, nor do I think I ever had.

**Comment by ChickenNuggers** [comment]
Users who don't log in for 30 days get their processes killed. If you want to recover the account, it would be acecptable for you to send one of the administrators a public key to use instead.

**Comment by KellerFuchs** [comment]
#70 takes care of most of those issues (but is currently buggy), please review.

**Comment by KellerFuchs** [comment]
Should be good now.
