### ISSUE TITLE
Unexpected "("

### ISSUE THREAD

**Issue by singlerider** [hashbang/hashbang.sh#47]
Right after ssh identification, every time:

"""
Now we will need an SSH Public Key.
 
 SSH Keys are a type of public/private key system that let you identify
 yourself to systems like this one without ever sending your password 
 over the internet, and thus by nature we won't even know what it is
 No SSH key for login to server found, attempting to generate one
 
 Path to new or existing connection key (~/.ssh/id_rsa): /etc/ssh/sengelman
 
 Using public key /etc/ssh/sengelman.pub
/dev/fd/63: 386: /dev/fd/63: Syntax error: "(" unexpected
"""

**Comment by singlerider** [comment]
More info, just saw this at the beginning of the process:

"""
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15619  100 15619    0     0   3320      0  0:00:04  0:00:04 --:--:--  3321
/dev/fd/63: 1: /dev/fd/63: -----BEGIN: not found
/dev/fd/63: 2: /dev/fd/63: Hash:: not found
"""

**Comment by ChickenNuggers** [comment]
Thanks for your concern on the errors in this script. While we tell users to use `sh` when running the script, we accidentally removed compatibility for any shell other than `zsh` or `bash`. Please use either `zsh` or `bash` instead of any other shell when running this script while we finish fixing up this issue.

**Comment by AlissaSquared** [comment]
Sorry about the long time taking to update this. This issue has been resolved and waiting for a merge.
