### ISSUE TITLE
Host value needs to be checked when registering

### ISSUE THREAD

**Issue by CTassisF** [hashbang/hashbang.sh#58]
Hello.

I just registered two users using the "advanced method" but I can't login using my keys (it keeps asking for user passwords - not SSH keys passwords).

```
$ curl -d '{"user":"cesar","key":"'"$(cat ~/.ssh/id_rsa.pub)"'","host":"cesar.hashbang.sh"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
{"message": "success"}
```

```
$ curl -d '{"user":"ctf","key":"'"$(cat ~/.ssh/id_dsa.pub)"'","host":"ctf.hashbang.sh"}' -H 'Content-Type: application/json' https://hashbang.sh/user/create
{"message": "success"}
```

Can you please check what happened?

Thanks in advance.

**Comment by ChickenNuggers** [comment]
Hm. You weren't supposed to get success messages. We have four servers that clients can connect to (the host field specifies which one) and you apparently don't have one?
We'll migrate you (and hopefully others) as soon as possible.
For now, just ssh to {ny1,to1,da1,sf1}.hashbang.sh

**Comment by ChickenNuggers** [comment]
Eventually this should get fixed when we have the DNS server able to redirect you to your server.

**Comment by ChickenNuggers** [comment]
I changed the title to what the actual issue is, if you don't mind.

**Comment by KellerFuchs** [comment]
I need someone to proofread both pull requests, I'm really not much of a Python person.

**Comment by KellerFuchs** [comment]
Ok, that has been merged now.

Of course, it's broken but #67 should fix it.
