### ISSUE TITLE
chsh and passwd broken

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [hashbang/hashbang.sh#65]
Due to the passwordless setup users are given by default, there is no way to set a password nor change the login shell.

````
$ passwd
Current Password: <does not matter what you type here>
passwd: Authentication token manipulation error
passwd: password unchanged
$ chsh
chsh: PAM: Permission denied
$ 
````

**Comment by ChickenNuggers** [comment]
User accounts are managed via the (currently broken) `hashbangctl` command. Since users have their accounts managed through LDAP, this way users can manage their accounts across all servers.

**Comment by KellerFuchs** [comment]
@ChickenNuggers Could you reming me how `#!ctl` is broken?

Actually, you shoud open an issue for it.
