### ISSUE TITLE
Systemd units. Sudo. Pass.

### ISSUE THREAD

**Issue by makerbeleg** [hashbang/hashbang.sh#77]
Is there way to start or enable my own systemd units? It requires a sudo which requires a user password which I do not know cause I was authenticated with key.

**Comment by daurnimator** [comment]
Use `systemctl --user`

**Comment by ChickenNuggers** [comment]
This is misfiled. If you think there should be a notification, make a pull request at [shell-etc](/hashbang/shell-etc) for /skel/welcome.msg.

**Comment by makerbeleg** [comment]
Yes. indeed. Thank you.
And yeah, notification would be nice about that.
