### ISSUE TITLE
Internal Server Error on ServerStats

### ISSUE THREAD

**Issue by DosAmp** [hashbang/hashbang.sh#80]
I have tried running the hashbang.sh script several times since last week and it always bailed early because https://hashbang.sh/server/stats returned with 500 Internal Server Error (both as HTTP status code and JSON response).

As the LDAP server is apparently not down (connection to ldap.hashbang.sh:389 succeeds), maybe it would be useful to add [general exception handling as in `UserCreate`](https://github.com/hashbang/hashbang.sh/blob/4ce48ceec9db671972822992b4b7cbb415ba3d03/server.py#L92) to `ServerStats` as well?

**Comment by DosAmp** [comment]
(Sorry, this is a duplicate of #79. My bad.)

**Comment by KellerFuchs** [comment]
@DosAmp Thanks for the report, and resolved.
Might have a stab at a more permanent solution.

**Comment by KellerFuchs** [comment]
@DosAmp This issue has been permanently fixed, btw.
