### ISSUE TITLE
`[ $?` anti-pattern

### ISSUE THREAD

**Issue by lahemi** [hashbang/hashbang.sh#89]
`cmd; if [ $? -eq 0 ]` and `cmd; if [ $? -ne 0 ]` are redundant, as you are checking the return value of `[`.

`if` expects a command, meaning you can do `if cmd; ...; fi`.

**Comment by KellerFuchs** [comment]
@lahemi Thanks.
If you don't mind, I will first patch the linter we use to detect this anti-pattern, because the best fixes are fixes where you make sure you don't make the same error again  ;-)

**Comment by lahemi** [comment]
Sure, that's obviously a better way to approach this : )

**Comment by KellerFuchs** [comment]
See https://github.com/koalaman/shellcheck/issues/726 for the associated ShellCheck issue.
Turns out that this is much trickier than expected.
